linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - govet
    - golint
    - gocyclo
    - maligned
    - dupl
    - goconst
    - misspell
