# fly.toml app configuration file generated for hackmud-prometheus-exporter on 2023-12-18T01:27:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hackmud-prometheus-exporter"
primary_region = "atl"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[metrics]
  port = 8080
  path = "/metrics"